using System;
using System.Collections.Generic;
using MadeBySeth.Cv.Api.Core;
using System.Threading.Tasks;

namespace MadeBySeth.Cv.Data
{
    public class WorkRecordRepository : IWorkRecordRepository
    {
        /// <summary>
        /// Currently just hardcoded rather than coming from a data source
        /// </summary>
        /// <returns>List of work records</returns>
        public async Task<IEnumerable<WorkRecord>> GetAll()
        {
            return new List<WorkRecord>
            {
               new WorkRecord { Id = 6, Title = "Software Engineer", Company = "Made By Seth Ltd, Leeds, UK", StartDate= new DateTime(2017, 2, 1), EndDate= new DateTime(2017, 3, 1), Summary= "Interested in some new technologies so created a project for myself to create Angular 2 site for my CV which utilised a .NET Core WebAPI that was hosted in Azure. Created my first .NET Core project for a WebAPI using Visual Studio 2017 for the Angular 2 site to retrieve data from and deployed and hosted the WebAPI site in Azure as a web app. http://angular.madebyseth.com. Code is on https://github.com/sniemuth/profile-site.", Technologies = new List<string> {"C#", ".NET Core", "WebAPI", "Azure Web App", "Angular2", "Git" }, KeyAchievements = new List<string> { } },
               new WorkRecord { Id = 5, Title = "Contract Developer (2 extensions)", Company = "SSP Worldwide, Halifax, UK", StartDate= new DateTime(2016, 2, 1), EndDate= new DateTime(2016, 12, 1), Summary= "Continuous provision of support and addition of relevant features to several insurance products at aninternational financial corporation. Separated MVC web applications communicating across WCF and WebAPI. Utilised TFS for source control, CI, deployments, nuget packaging and to track progress of bugs, tasks, user stories and epics.", Technologies = new List<string> {"C#", ".NET 4.x", "MVC", "WebAPI", "WCF/Web Services", "Unity", "Entity Framework", "MS SQL", "jQuery", "KnockoutJS", "TFS", "Selenium", "SpecFlow" }, KeyAchievements = new List<string> {"Implemented a fully automated testing suite to run every night using TFS, Selenium and SpecFlow", "Converted limited requirements into coherent fully featured solutions with documentation", "Worked to implement best practices into code base with refactor work to add EF migrations, separation, between distinct products and appropriate service and data layers, and more coherent DI implementation", "Created plan to fully automate deployments into cumbersome UAT and production environments using TFS and windows services", "Proactively work to identify and fix problems with consensus from team as well as help the rest of the team more quickly identify the problems using CI and testing" } },
               new WorkRecord { Id = 4, Title = "Contract Developer (6 extensions)", Company = "ControlF1, Huddersfield, UK", StartDate= new DateTime(2014, 12, 1), EndDate= new DateTime(2016, 1, 1), Summary= "Developed the telematics system of a leading vehicle breakdown cover and insurance company by fixing bugs and adding features. Hosted on AWS which made use of MVC sites, WCF services, SNS messages, SQS queues with a backing of DynamoDB and MySQL. Continuous integration using TeamCity and source control with Git. Utilised JIRA to keep track of sprints, features, user stories, tasks, bugs and time. Unit and integration test writing as part of TDD with code reviews done part of every pull request.", Technologies = new List<string> {"C#", ".NET 4.x", "MVC", "AWS", "Elastic Beanstalk", "WCF/Web Services", "Ninject", "DynamoDB", "Lambda", "NodeJS and Grunt", "SNS", "SQS", "MySQL", "jQuery", "KnockoutJS", "Agile Kanban", "TeamCity", "Git" },  KeyAchievements = new List<string> {"Initiated and saw to completion several important pieces of refactoring such as a rework of the Dependency Injection setup using Ninject", "Saw to completion several pieces of work to add features and stability to the product", "Developed and implemented one click deployment release process from TeamCity to Elastic Beanstalk", "Provided solution architecture direction with a web based approach and background", "Essential part of redeveloping architecture for AWS cloud hosted solution", "Was able to shift quickly between contexts to help meet the needs of the client" } },
               new WorkRecord { Id = 3, Title = "Software Developer", Company = "thebigword, Leeds, UK", StartDate= new DateTime(2014, 4, 1), EndDate= new DateTime(2014, 11, 1), Summary= "Part of large team rewriting a translation management system. Large system interacting across WCF, RabbitMQ messages, SignalR and WebAPI. Mostly MVC web applications with WCF service layer interacting with EF (code-first migrations) SQL server database utilising asynchronous calls. Continuous integration and deployment using TeamCity and source control with SVN. Utilised TargetProcess and Kanban boards to keep track of features, user stories, tasks, bugs and time in agile environment. Unit and integration test writing as part of TDD with mandatory code reviews. ", Technologies = new List<string> {"C#", ".NET 4.x", "MVC", "WCF/Web Services", "Ninject", "Entity Framework", "MS SQL", "WebAPI", "Javascript", "jQuery", "KnockoutJS", "KendoUI", "TeamCity", "Automapper", "Postsharp", "Multi-Threading", "Agile Kanban", "TargetProcess" },  KeyAchievements = new List<string> {"Spearheaded refactor of largest solution in system to introduce manager layer between service layer and repository layers to allow for maximum code reuse without sacrificing performance","Developed and implemented reusable mapping library utilising Automapper", "Developed and implemented reusable, high performance attribute based caching library utilising PostSharp and Redis", "Developed and implemented attribute based security with pre-emptive unit tests to ensure system continued to stay secure", "Creation of slick KendoUI and KnockoutJS interfaces", "Delivering software on tight deadlines" } },
               new WorkRecord { Id = 2, Title = "Senior Web Application Developer", Company = "Equator, Glasgow, UK", StartDate= new DateTime(2010, 3, 1), EndDate= new DateTime(2013, 08, 1), Summary= "Complete system rewrite for the largest solicitor property centre in the north east of Scotland using latest technologies and agile scrum methodology. Extensive work with Umbraco, an open source CMS written in C#/.NET, on many large commercial customer facing websites. Development of e-commerce sites using the open source C#/.NET nopCommerce.", Technologies = new List<string> {"C#", ".NET 4.x", "MVC", "MS SQL", "SSIS", "Entity Framework", "WebAPI", "less", "Javascript", "jQuery", "KnockoutJS", "umbraco", "nopCommerce", "Ninject", "Castle", "TFS", "SVN", "CruiseControl", "Agile Scrum", "Waterfall"},  KeyAchievements = new List<string> {"Solutions architect of the complete rewrite of the property solicitor back-end system", "Created an SSIS package for a CSV export", "Use of EF for CRUD operations", "Utilisation of scrum and agile methodologies including three week sprints and daily morning huddles", "Implementation of KnockoutJS and more advanced CSS3 features as part of backend system", "Sole developer on smaller projects creating all front - end and back end code as well as senior / lead developer on large projects with up to 8 dedicated team members", "Delivery of projects on time and under budget", "Maintenance of company common utilities and Umbraco white label for quick start up on projects which included moving our common utilities into Nuget packages", "Client interaction including on - site visits, training, conference calls and emails", "Extensive collaboration and work as part of teams composed of technical and non-technical members", "Bespoke e-commerce solutions extending the capabilities of nopCommerce with new components, shipping provider and import / export services" } },
            };
        }
    }
}
